language: node_js
node_js:
  - "8"
script:
  - npm run build
after_success:
  - cp ./CNAME ./dist/CNAME
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "./dist/"
  github_token: $GITHUB_TOKEN
  on:
    branch: master
cache:
  directories:
    - "node_modules"
